export const services = [
  {
    id: 'pc-service',
    title: 'Service PC',
    description: 'Perbaikan hardware, software, upgrade komponen, hingga optimasi performa.',
    icon: 'FaDesktop',
    features: [
      'Perbaikan motherboard dan komponen',
      'Instalasi dan repair OS',
      'Upgrade RAM, SSD, VGA',
      'Optimasi performa',
      'Bersihkan debu dan maintenance',
    ],
    price: 'Mulai Rp 50.000',
  },
  {
    id: 'laptop-service',
    title: 'Service Laptop',
    description: 'Ganti LCD, keyboard, battery, cleaning, dan troubleshooting sistem.',
    icon: 'FaLaptop',
    features: [
      'Ganti LCD dan layar',
      'Ganti keyboard dan touchpad',
      'Ganti battery dan charger',
      'Cleaning dan thermal paste',
      'Troubleshooting sistem',
    ],
    price: 'Mulai Rp 75.000',
  },
  {
    id: 'printer-service',
    title: 'Service Printer',
    description: 'Perbaikan printer inkjet & laser, refill tinta, dan perawatan rutin.',
    icon: 'FaPrint',
    features: [
      'Perbaikan printer inkjet dan laser',
      'Refill tinta dan cartridge',
      'Perawatan rutin',
      'Unblock head printer',
      'Instalasi driver',
    ],
    price: 'Mulai Rp 50.000',
  },
  {
    id: 'networking',
    title: 'Networking',
    description: 'Instalasi LAN, WiFi, konfigurasi server, dan keamanan jaringan.',
    icon: 'FaNetworkWired',
    features: [
      'Instalasi LAN dan WiFi',
      'Konfigurasi router dan switch',
      'Setup server dan NAS',
      'Keamanan jaringan',
      'Troubleshooting jaringan',
    ],
    price: 'Konsultasi Gratis',
  },
]
